services:
  minio:
    container_name: minio
    image: quay.io/minio/minio:RELEASE.2025-04-22T22-12-26Z
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_REGION: eu-central-1
    healthcheck:
      test: ["CMD", "mc", "ready", "local"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - minio_data:/data
    command: server /data --console-address ":9001"

  postgres:
    container_name: postgres
    image: postgres:18.0
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d postgres -U postgres"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    depends_on:
      postgres:
        condition: service_healthy
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: pgadmin
      PGADMIN_LISTEN_PORT: 8888
      PGADMIN_DISABLE_POSTFIX: true
      GUNICORN_ACCESS_LOGFILE: "/dev/null"
    ports:
      - "8888:8888"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin_config/servers.json:/pgadmin4/servers.json
      - ./pgadmin_config/preferences.json:/pgadmin4/preferences.json

  asset_server:
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    image: gitea.home.anonymus09.com/admin/asset_server:latest
    container_name: asset_server
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres/game
      S3_ACCESS_KEY: SGrID2dcQbBjAxikEEzb
      S3_SECRET_KEY: rWpoNljCWJqrtqlltfCdbXDcNW1qZNGgorLgnKb0
      S3_API_URL: http://minio:9000
      SERVER_IP_PORT: 127.0.0.1:3001
    ports:
      - "3001:3001"

  asset_manager:
    depends_on:
      - asset_server
    image: gitea.home.anonymus09.com/admin/asset_manager:latest
    container_name: asset_manager
    ports:
      - "3000:3000"

volumes:
  minio_data:
  postgres_data:
  pgadmin_data:
