name: Asset Manager

on:
  push:
    paths:
      - "tools/asset_manager/**"
      - ".github/workflows/asset_manager.yml"
    branches:
      - "master"
      - "main"

jobs:
  build:
    runs-on: build
    steps:
      - uses: actions/checkout@v5

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Cache Docker layers
        uses: actions/cache@v4
        with:
          path: ${{ runner.temp }}/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to private Gitea instance
        uses: docker/login-action@v3
        with:
          registry: https://gitea.home.anonymus09.com
          username: ${{ vars.GITEA_USER }}
          password: ${{ secrets.GITEA_PASSWD }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ./tools/asset_manager
          file: ./tools/asset_manager/Dockerfile
          push: true
          tags: gitea.home.anonymus09.com/admin/asset_manager:latest
          cache-from: type=local,src=${{ runner.temp }}/.buildx-cache
          cache-to: type=local,dest=${{ runner.temp }}/.buildx-cache-new,mode=max

      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf ${{ runner.temp }}/.buildx-cache
          mv ${{ runner.temp }}/.buildx-cache-new ${{ runner.temp }}/.buildx-cache
