name: Deploy Services

# Only trigger, when the build workflow succeeded
on:
  push:
    paths:
      - ".github/workflows/deploy.yml"
    branches:
      - "master"
      - "main"

  workflow_run:
    workflows:
      [
        "Asset Manager - build",
        "Asset Server - build",
        "Prisma DB config - build",
      ]
    types:
      - completed

jobs:
  deploy:
    runs-on: srv
    steps:
      - uses: actions/checkout@v5

      - name: Create deploy folder
        run: |
          mkdir -p ~/deploy
          mkdir -p ~/deploy/pgadmin_config

      - name: Copy files
        run: |
          cp ./docker-compose.yml ~/deploy/docker-compose.yml
          cp ./tools/minio_init.sh ~/deploy/minio_init.sh
          cp ./tools/pgadmin_config/preferences.json ~/deploy/pgadmin_config/preferences.json
          cp ./tools/pgadmin_config/servers.json ~/deploy/pgadmin_config/servers.json

      - name: Update and run compose
        run: |
          docker compose pull && docker compose up -d

      - name: Prune docker
        run: |
          docker system prune -f
